project:
  type: website
  output-dir: docs

website:
  title: ""
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: materials/00-setup/index.qmd
        text: Setup
      - href: materials/01-intro/index.qmd
        text: Intro to Quarto
      - href: materials/02-presentations/index.qmd
        text: Presentations
      - href: materials/03-dashboards/index.qmd
        text: Dashboards
      - href: materials/04-typst/index.qmd
        text: PDFs
      - href: materials/05-websites/index.qmd
        text: Websites
      - href: materials/06-byob/index.qmd
        text: Creating and Sharing

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


