project:
  type: website
  output-dir: docs

website:
  title: ""
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: materials/00-setup/index.qmd
        text: Setup
      - href: materials/01-intro/index.qmd
        text: Intro to Quarto
      - href: materials/02-presentations/index.qmd
        text: Presentations
      - href: materials/03-dashboards/index.qmd
        text: Dashboards

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



